exports.FB_CLIENT_ID = process.env.FB_CLIENT_ID || ''
exports.FB_CLIENT_SECRET = process.env.FB_CLIENT_SECRET || ''
exports.FB_APP_TOKEN = process.env.FB_APP_TOKEN || ''
exports.FB_REDIRECT_URL = process.env.FB_REDIRECT_URL || ''
exports.SESSION_KEYS = process.env.SESSION_KEYS || 'sample-session-keys'